INSERT INTO activities (name, activity_group_id) VALUES ('Strength Training', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Cardio', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Yoga', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Pilates', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Dance', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Meditation', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Breathing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Stretching', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Walking', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Running', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Cycling', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Swimming', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Rowing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Hiking', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Climbing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Skiing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Snowboarding', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Surfing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Skateboarding', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Rollerblading', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Ice Skating', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Snowshoeing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Cross Country Skiing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Core Training', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Balance Training', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Bowling', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Golf', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Tennis', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Soccer', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Basketball', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Volleyball', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Football', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Baseball', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Softball', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Rugby', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Hockey', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Lacrosse', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Ultimate Frisbee', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Cricket', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Badminton', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Table Tennis', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Pickleball', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Racquetball', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Squash', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Handball', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Boxing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Martial Arts', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Wrestling', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Jiu Jitsu', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Karate', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Climbing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Parkour', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Skateboarding', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Rollerblading', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Ice Skating', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Snowshoeing', 1);
INSERT INTO activities (name, activity_group_id) VALUES ('Cross Country Skiing', 1);
