services:

  postgres:
    container_name: postgres
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: 'Asia/Bishkek'
      PGTZ: 'Asia/Bishkek'
    ports:
      - "${db_port}:${db_port}"
    restart: unless-stopped

  app:
    container_name: app
    build: .
    volumes:
      - ./logs:/logs
      - ./secrets:/secrets
    env_file:
      - .env
    ports:
      - "${port}:${port}"
    depends_on:
      - postgres
    restart: unless-stopped

  migrate:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./bin/migrate", "-up" ]
    depends_on:
      - postgres

  seed:
    build:
      context: .
      dockerfile: Dockerfile
    command: [ "./bin/seed"]
    depends_on:
      - postgres

volumes:
  pg-data: